version: '3.3'
services:
  php-fpm:
    build: ./php/
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www:rw
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
    restart: always
    command: php-fpm
  nginx:
    build: ./nginx
    depends_on:
      - php-fpm
    links:
      - php-fpm:php-fpm
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www:rw
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../logs/nginx:/var/log/nginx
    restart: always
    command: nginx -g 'daemon off;'